create database bbds;
use bbds;
INSERT INTO produto (codigo, nome, valor, descricao, qtd, keyword, promo) VALUES
(1, 'Câmera Intelbras Wi-Fi iM3 C', 289.90, 'Câmera de segurança interna Full HD 1080p com visão noturna infravermelha, detecção de movimento, áudio bidirecional e conexão Wi-Fi. Compatível com o aplicativo Intelbras Mibo para monitoramento remoto via smartphone.', 45, 'seguranca, camera wifi, intelbras mibo', 279.90),
(2, 'Roteador Intelbras Twibi Fast', 450.00, 'Sistema Wi-Fi Mesh dual band com cobertura de até 120m², eliminando pontos cegos. Fácil configuração pelo aplicativo, suporte a múltiplos dispositivos simultâneos e tecnologia de roaming inteligente.', 20, 'rede, roteador mesh, wifi', 0.00),
(3, 'Fechadura Digital Intelbras FR 101', 399.00, 'Fechadura eletrônica de sobrepor com senha numérica de 6 dígitos, acabamento robusto em metal e compatibilidade com portas de madeira. Possui alarme anti-intrusão e bateria de longa duração.', 30, 'casa inteligente, fechadura digital', 350.90),
(4, 'Telefone Sem Fio Intelbras TS 3110', 159.00, 'Telefone digital sem fio com tecnologia DECT 6.0, identificador de chamadas, viva-voz, agenda para até 50 contatos e design ergonômico com display iluminado.', 100, 'telefonia, telefone fixo', 0.00),
(5, 'Nobreak Intelbras XNB 720', 420.00, 'Nobreak com potência de 720VA/360W, proteção contra surtos, subtensão e sobretensão. Ideal para computadores e equipamentos eletrônicos sensíveis, com autonomia de até 30 minutos em caso de queda de energia.', 15, 'energia, nobreak, protecao', 380.00),
(6, 'Vídeo Porteiro Intelbras IVR 1010', 580.00, 'Sistema de vídeo porteiro com tela colorida de 4,3 polegadas, visão noturna, comunicação de voz bidirecional e acionamento remoto de fechadura. Instalação simples sem necessidade de fiação adicional.', 12, 'interfonia, video porteiro', 0.00),
(7, 'Fechadura Intelbras IFR 7001 Preta', 1199.00, 'Fechadura digital de embutir sem maçaneta com biometria, senha numérica e cartão RFID. Compatível com portas de madeira de até 90mm, com registro de até 100 digitais e histórico de acessos via aplicativo.', 5, 'fechadura, automacao residencial, seguranca', 0.00),
(8, 'Arandela Solar Intelbras ASI 500 Dual Color', 341.91, 'Kit com 2 arandelas solares integradas com painel fotovoltaico embutido, sensor de presença e dupla temperatura de cor (branco frio e branco quente). Sem necessidade de fiação elétrica, instalação simples e econômica.', 4, 'energia solar, iluminacao, arandela', 300.00),
(9, 'Sensor de Presença Intelbras ESPI 360 A', 28.71, 'Sensor de presença para iluminação com cobertura de 360°, alcance de até 8m e temporização ajustável. Instalação em teto ou parede, compatível com lâmpadas incandescentes, fluorescentes e LED.', 35, 'sensor de presenca, iluminacao, economia de energia', 22.00),
(10, 'Protetor Elétrico Intelbras EPS 302', 580.00, 'Dispositivo de proteção elétrica bivolt com 2 tomadas, proteção contra surtos de tensão, raios e variações da rede elétrica. Indicado para equipamentos de alto valor como TVs, computadores e home theaters.', 255, 'dispositivo de protecao, eletricidade, seguranca', 0.00),
(11, 'Kit Protetor Elétrico Intelbras EPS 301 Preto', 125.64, 'Kit com 4 dispositivos de proteção contra surtos de tensão, com tomada padrão NBR e LED indicador de funcionamento. Ideal para proteger eletrodomésticos e equipamentos eletrônicos do dia a dia.', 12, 'dispositivo de protecao, eletricidade, seguranca', 110.00),
(12, 'Switch Gigabit Intelbras 24 Portas S1124G', 829.88, 'Switch não gerenciável com 24 portas Gigabit, gabinete em metal, capacidade de switching de 48Gbps e suporte a alta densidade de conexões. Ideal para redes corporativas e ambientes que exigem alto tráfego de dados.', 10, 'switch, rede, gigabit', 799.00),
(13, 'Switch Hi-PoE Intelbras 5 Portas SF 500', 569.21, 'Switch Fast Ethernet com 5 portas e suporte a PoE de longa distância (até 250m), alimentando câmeras e dispositivos IP sem necessidade de fonte separada. Plug and play, sem necessidade de configuração.', 20, 'switch, rede, poe', 520.00),
(14, 'Cartão MicroSD Intelbras 64GB', 148.41, 'Cartão de memória microSD 64GB WD Purple desenvolvido para gravação contínua em câmeras de segurança, com alta durabilidade, velocidade de leitura de até 100MB/s e 3 anos de garantia.', 99, 'cartao de memoria, microSD, armazenamento', 0.00),
(15, 'Kit Lâmpada Smart Intelbras Wi-Fi EWS 410', 141.82, 'Kit com 2 lâmpadas inteligentes Wi-Fi com controle por voz (Alexa e Google Assistente) ou pelo aplicativo IzySmart. Ajuste de intensidade e temperatura de cor, programação de horários e consumo eficiente.', 12, 'lampada smart, automacao, iluminacao', 69.90),
(16, 'Cabo Intelbras USB-A para Lightning 1,2m', 69.91, 'Cabo Lightning certificado com revestimento em PVC resistente, conector reforçado e suporte a carga rápida e transferência de dados de alta velocidade. Compatível com iPhones e iPads.', 221, 'cabo, usb, lightning', 0.00),
(17, 'Carregador Intelbras USB 20W EC 11', 74.91, 'Carregador compacto de 20W com 2 saídas USB (USB-A e USB-C), compatível com carregamento rápido PD e QC. Proteção contra sobrecarga, curto-circuito e superaquecimento.', 12, 'carregador, usb, power', 0.00),
(18, 'Carregador de Mesa Intelbras GaN 240W EC 40', 649.90, 'Carregador de mesa com 4 saídas USB-C e tecnologia GaN de alta eficiência, suportando até 240W totais. Ideal para carregar simultaneamente notebooks, tablets e smartphones com carregamento rápido.', 12, 'carregador, usb, power', 0.00);
insert into admin(codigo,senha) values(1234,"abcd");
select * from contato;
select c.nome, p.nome, ped.codigo from pedido as ped join cliente as c on cliente_codigo=c.codigo join pedido_produtos on pedido_id=ped.codigo join produto as p on produto_id=p.codigo where ped.codigo =13;